import 'package:flutter/material.dart';
import 'package:quizai/utils/app_styles.dart';


class QuizScreen extends StatefulWidget {
    const QuizScreen ({super.key, required this.title});

    final String title;

    @override
        State<QuizScreen> createState() => _QuizScreenState();
}

enum Anwsers {A, B, C, D, N}
class _QuizScreenState extends State<QuizScreen> {

    double _screenWidth = 1000;

    int _selectedQuestion = 1;
    String _subject = "Math (hehe)";
    String _question = "this is some random question that hopefully was generated by chat GPT, hopefully....";
    String _anwserA = "this is some example anwser A";
    String _anwserB = "this is some example anwser B";
    String _anwserC = "this is some example anwser C";
    String _anwserD = "this is some example anwser D";
    Anwsers? _anwser = Anwsers.N;

    final double _quizFormWidth = 600;


    Widget questionIndicatorButton(int questionNumber) {
        return Padding(
                padding: const EdgeInsets.all(5),
                child: IconButton(
                    style: IconButton.styleFrom(
                        backgroundColor: questionNumber == _selectedQuestion? AppTheme.accent : AppTheme.secondary,
                        ),
                    constraints: const BoxConstraints(minWidth: 20, maxWidth: 25, minHeight: 10, maxHeight: 10),
                    icon: Container(),
                    onPressed: () {
                    setState(() {
                            _selectedQuestion = questionNumber;
                            });
                    },
                    ),
                );
    }

    Widget bottomButton(String text, IconData icon, IconAlignment iconAlignment, VoidCallback? pressed) {
        return ElevatedButton.icon(
                label: Text(text, style: TextStyle(color: AppTheme.white)),
                icon: Icon(icon, color: AppTheme.white),
                iconAlignment: iconAlignment,
                onPressed: pressed,
                style: ElevatedButton.styleFrom(
                    backgroundColor: AppTheme.accent,
                    )
                );
    }

    Widget radioListButton(BuildContext context, String text, Anwsers val) {
        return Material(
                child: Container(
                    decoration: BoxDecoration(
                        border: Border.all(
                            color: AppTheme.primary,
                            width: 3,
                            )
                        ),
                    child: RadioListTile<Anwsers>(
                        tileColor: AppTheme.secondary,
                        selectedTileColor: AppTheme.accent,
                        activeColor: AppTheme.accent,
                        title: Text(text, style: const TextStyle(color: AppTheme.white)),
                        value: val,
                        groupValue: _anwser,
                        onChanged: (Anwsers? value) {
                        setState(() {
                                _anwser = value;
                                });
                        },
                        ),
                    ),
                    );
    }

    @override
        Widget build(BuildContext context) {
            _screenWidth = MediaQuery.sizeOf(context).width;

            return Scaffold(
                  body: Padding(
                          padding: EdgeInsets.only(top: 20, bottom: 20, left: 200, right: 200),
                          child: Container(
                              color: AppTheme.primary,
                              child: Padding(
                                  padding: EdgeInsets.all(20),
                                  child: Column(
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      children:[
                                      Row(
                                      children: [
                                      IconButton(
                                      onPressed: () {
                                          Navigator.pop(context);
                                      },
                                      icon: Icon(Icons.close_rounded, size: 30, color: AppTheme.accent),
                                      ),
                                      ]
                                      ),
                                      SizedBox(
                                          width: _quizFormWidth,
                                          child: Row(
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              children:[
                                              Text("Subject: $_subject", style:
                                                  const TextStyle(
                                                      color: AppTheme.accent,
                                                      fontWeight: FontWeight.bold,
                                                      fontSize: 25,
                                                      )
                                                  )
                                              ]
                                              ),
                                          ),
                                      Row(
                                          mainAxisAlignment: MainAxisAlignment.center,
                                          children: [
                                          questionIndicatorButton(1),
                                          questionIndicatorButton(2),
                                          questionIndicatorButton(3),
                                          questionIndicatorButton(4),
                                          questionIndicatorButton(5),
                                          questionIndicatorButton(6),
                                          questionIndicatorButton(7),
                                          questionIndicatorButton(8),
                                          ]
                                         ),
                                      Expanded(
                                              child: SizedBox(
                                                  width: _quizFormWidth,
                                                  child: Row(
                                                      mainAxisAlignment: MainAxisAlignment.center,
                                                      crossAxisAlignment: CrossAxisAlignment.center,
                                                      children: [
                                                      Flexible(child: Text(_question, style: TextStyle(color: AppTheme.white, fontSize: 25)))
                                                      ]
                                                      ),
                                                  ),
                                              ),
                                      Row(
                                              mainAxisAlignment: MainAxisAlignment.center,
                                              children: [
                                              SizedBox(
                                                  height: 260,
                                                  width: _quizFormWidth,
                                                  child: Column(
                                                      children: <Widget>[
                                                      radioListButton(context, _anwserA, Anwsers.A),
                                                      radioListButton(context, _anwserB, Anwsers.B),
                                                      radioListButton(context, _anwserC, Anwsers.C),
                                                      radioListButton(context, _anwserC, Anwsers.D),
                                                      ],
                                                      )
                                                  )
                                              ],
                                         ),
                                      Row(
                                              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                                              children:[
                                              Column(
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  children: [
                                                  bottomButton("Powrót", Icons.arrow_left_outlined, IconAlignment.start                                             
                                                      , _selectedQuestion <= 1? null : () {
                                                      setState((){_selectedQuestion--;});
                                                      })
                                                  ]
                                                  ),
                                              Column(
                                                  mainAxisAlignment: MainAxisAlignment.center,
                                                  children: [
                                                  bottomButton("Następne", Icons.arrow_right_outlined, IconAlignment.end, 
                                                      _selectedQuestion >= 8? null : () {
                                                      setState((){_selectedQuestion++;});
                                                      }),
                                                  ]
                                                  ),
                                              ]
                                                  )
                                                  ]
                                                  ),
                                              ),
                                              ),
                                              ),
            );
        }
}
